' AI Agent diagram
' With relevant classes and enums
' Created: 2025-10-08
' Last updated: 2025-10-14

@startuml ai-aiagent

set separator /

abstract "Core/SoftwareAgent" {
}

class "AI/AIAgent" extends "Core/SoftwareAgent" {
    + /Core/suppliedBy : /Core/Agent [0..*]
    + /Software/enabledByDefault : xsd:boolean [0..1]
    + /Software/inputModality : Core/Modality [0..*]
    + /Software/outputModality : Core/Modality [0..*]
    + automationLevel : AutomationLevel [0..1]
}

enum "AI/AutomationLevel" {
    autonomous
    fullAutomation
    highAutomation
    conditionalAutomation
    partialAutomation
    assistiveAutomation
    notAutomated
}

enum "Core/Modality" {
    audio
    gesturePose
    hapticTactile
    image
    noAssertion
    other
    text
    video
}

@enduml
