' AI Agent diagram
' With relevant classes and enums
' Created: 2025-10-08
' Last updated: 2025-10-08

@startuml AIAgent

set separator /

abstract "Core/SoftwareAgent" {
}

class "AI/AIAgent" extends "Core/SoftwareAgent" {
    + /Core/suppliedBy : /Core/Agent [0..*]
    + automationLevel : AutomationLevel [0..1]
}

enum "AI/AutomationLevel" {
    autonomous
    fullAutomation
    highAutomation
    conditionalAutomation
    partialAutomation
    assistiveAutomation
    notAutomated
}

@enduml
