' AI Agent diagram
' With relevant classes and enums
' Created: 2025-10-08
' Last updated: 2025-10-08

@startuml AIAgent

set separator /

abstract "Core/SoftwareAgent" {
}

class "AI/AIAgent" extends "Core/SoftwareAgent" {
    + /Core/suppliedBy : /Core/Agent [0..*]
    + /Software/enabledByDefault : xsd:boolean [0..1]
    + /Software/inputModality : Core/Modality [0..*]
    + /Software/outputModality : Core/Modality [0..*]
    + automationLevel : AutomationLevel [0..1]
}

enum "AI/AutomationLevel" {
    autonomous
    fullAutomation
    highAutomation
    conditionalAutomation
    partialAutomation
    assistiveAutomation
    notAutomated
}

enum "Core/Modality" {
    audioSpeech
    audioNonSpeech
    code
    geometry2d
    geometry3d
    gesturePose
    hapticTactile
    image
    other
    tabular
    text
    timeseries
    video
}

@enduml
